### Login como user e lista todos os usuarios cadastrados na base de dados

@baseUrlHttp = http://localhost:5135/api/v1
@baseUrlHttps = https://localhost:7174/api/v1

# @name login
POST {{baseUrlHttp}}/auth/login
Content-Type: application/json

{
  "email": "user@fiapgames.com",
  "password": "userFG123!"
}
###
@authToken = {{login.response.body.$.accessToken}}
GET {{baseUrlHttp}}/users
Authorization: Bearer {{authToken}}
###
